name: Project Absence CI (Lint & Test)

on: [push]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run rustfmt
        run: cargo fmt --all -- --check --verbose
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [rustfmt, clippy]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies for clipboard crate
        run: sudo apt-get install -y libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build
        run: cargo build --all --no-default-features --all-features
      - name: Test
        run: cargo test --all --no-default-features --all-features
