name: Project Absence CI (Lint & Test)

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Run rustfmt
        run: cargo fmt --all -- --check --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Install dependencies for clipboard crate
        run: sudo apt-get install -y libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Build
        run: cargo build --all --no-default-features --all-features
      - name: Test
        run: cargo test --all --no-default-features --all-features